import mumaker from 'mumaker';
import { getBotName } from '../setting/botAssets.js';

// On utilise directement les IDs extraits des URLs
const TEXT_TYPES = {
  metallic: "798", ice: "101", snow: "621", impressive: "801",
  matrix: "154", light: "648", neon: "797", devil: "683",
  purple: "100", thunder: "97", leaves: "153", arena: "360",
  hacker: "677", sand: "582", blackpink: "810", glitch: "767",
  fire: "372", '1917': "523"
};

const formatTypes = () => Object.keys(TEXT_TYPES).map(t => `• ${t}`).join('\n');

export default {
  name: 'textmaker',
  alias: ['textgen', 'ephoto', 'tm'],
  category: 'Tools',
  description: 'Generates stylish text with different ePhoto360 effects',

  async execute(kaya, mek, from, args, prefix) {
    try {
      const sender = mek.sender;
      const botName = getBotName(sender);
      
      const type = args[0]?.toLowerCase();
      const text = args.slice(1).join(' ').trim();

      if (!type || !TEXT_TYPES[type]) {
        return await kaya.sendMessage(from, { text: `▉ \`${botName}\` ▉\n▰▰▰▰▰▰▰▰▰▰▰▰▰\n*❌ INCORRECT USAGE*\n\n📌 *Usage*: \`${prefix}textmaker <type> <text>\`\n\n🎨 *Available types*:\n${formatTypes()}` }, { quoted: mek });
      }

      if (!text) {
        return await kaya.sendMessage(from, { text: `❌ *Missing text*\n📌 Example: \`${prefix}textmaker ${type} Kaya\`` }, { quoted: mek });
      }

      await kaya.sendPresenceUpdate('composing', from);

      // mumaker.ephoto attend généralement l'ID (ou le lien complet si la lib est mise à jour)
      // Si avec l'ID ça ne marche pas, essaie `TEXT_TYPES[type]` comme URL complète
      const result = await mumaker.ephoto(TEXT_TYPES[type], text);

      // La structure de retour de mumaker est souvent result.url ou result.image
      const imageUrl = result?.url || result?.image;

      if (!imageUrl) throw new Error('Image not generated by API');

      return await kaya.sendMessage(from, {
        image: { url: imageUrl },
        caption: `✨ *GENERATED BY ${botName.toUpperCase()}* ✨`
      }, { quoted: mek });

    } catch (err) {
      console.error('❌ textmaker error:', err);
      return await kaya.sendMessage(from, { text: `❌ Unable to generate image.\nError: ${err.message}` }, { quoted: mek });
    }
  }
};
